In [1]:
import pandas as pd

In [3]:
df= pd.read_csv("C:/Users/selvi/Downloads/practice_retail_data.csv")
df

,order_id,product_name,category,quantity,unit_price,order_date,region
0,1001,Chicken Breast,Meat,2.0,14.63,2026-01-06,East
1,1002,Greek Yogurt,Dairy,3.0,3.28,2026-02-18,East
2,1003,Frozen Pizza,Frozen,1.0,5.69,2026-02-24,East
3,1004,Greek Yogurt,Dairy,4.0,5.69,2026-01-21,North
4,1005,Chicken Breast,Meat,2.0,8.61,2026-02-27,South
...,...,...,...,...,...,...,...
95,1096,Sourdough Bread,Bakery,1.0,4.51,2026-03-29,East
96,1097,Avocados,Produce,1.0,8.17,2026-01-18,East
97,1098,Whole Milk,Dairy,3.0,13.89,2026-02-15,North
98,1099,Avocados,Produce,1.0,5.54,2026-01-22,South
99,1100,Frozen Pizza,Frozen,5.0,5.32,2026-01-29,South

In [4]:
df.head(5)

   order_id    product_name category  quantity  unit_price  order_date region
0      1001  Chicken Breast     Meat       2.0       14.63  2026-01-06   East
1      1002    Greek Yogurt    Dairy       3.0        3.28  2026-02-18   East
2      1003    Frozen Pizza   Frozen       1.0        5.69  2026-02-24   East
3      1004    Greek Yogurt    Dairy       4.0        5.69  2026-01-21  North
4      1005  Chicken Breast     Meat       2.0        8.61  2026-02-27  South

In [5]:
#setting index to one of the cols in the dataframe
df.set_index('order_id',inplace=True)

In [6]:
df.head(5)

            product_name category  quantity  unit_price  order_date region
order_id
1001      Chicken Breast     Meat       2.0       14.63  2026-01-06   East
1002        Greek Yogurt    Dairy       3.0        3.28  2026-02-18   East
1003        Frozen Pizza   Frozen       1.0        5.69  2026-02-24   East
1004        Greek Yogurt    Dairy       4.0        5.69  2026-01-21  North
1005      Chicken Breast     Meat       2.0        8.61  2026-02-27  South

In [17]:
#reading a non nested json file
jsondata = pd.read_json(r"C:\Users\selvi\Downloads\Amazon_1-level_1-KB_formatted.json")
jsondata

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.0,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.1,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298

In [19]:
import json

# Load raw JSON file
with open("C:/Users/selvi/Downloads/colors.json") as f:
    data = json.load(f)

# Flatten the 'colors' list into a DataFrame
jsondata = pd.json_normalize(data['colors'])
jsondata

         name      hex   category  rgb.r  rgb.g  rgb.b
0       Black  #000000    neutral      0      0      0
1       White  #FFFFFF    neutral    255    255    255
2         Red  #FF0000    primary    255      0      0
3       Green  #00FF00    primary      0    255      0
4        Blue  #0000FF    primary      0      0    255
5      Yellow  #FFFF00  secondary    255    255      0
6        Cyan  #00FFFF  secondary      0    255    255
7     Magenta  #FF00FF  secondary    255      0    255
8      Orange  #FFA500       warm    255    165      0
9        Pink  #FFC0CB       warm    255    192    203
10     Purple  #800080       cool    128      0    128
11     Violet  #EE82EE       cool    238    130    238
12      Brown  #A52A2A      earth    165     42     42
13     Maroon  #800000      earth    128      0      0
14      Olive  #808000      earth    128    128      0
15       Teal  #008080       cool      0    128    128
16       Navy  #000080       cool      0      0    128
17       Gray  #808080    neutral    128    128    128
18     Silver  #C0C0C0    neutral    192    192    192
19       Lime  #32CD32     nature     50    205     50
20       Aqua  #00CED1     nature      0    206    209
21      Coral  #FF7F50       warm    255    127     80
22     Salmon  #FA8072       warm    250    128    114
23      Khaki  #F0E68C      earth    240    230    140
24       Plum  #DDA0DD       cool    221    160    221
25       Gold  #FFD700       warm    255    215      0
26    Crimson  #DC143C       warm    220     20     60
27     Indigo  #4B0082       cool     75      0    130
28  Turquoise  #40E0D0     nature     64    224    208
29      Ivory  #FFFFF0    neutral    255    255    240
30      Beige  #F5F5DC    neutral    245    245    220
31   Lavender  #E6E6FA       cool    230    230    250
32       Mint  #98FF98     nature    152    255    152
33      Peach  #FFCBA4       warm    255    203    164
34      Slate  #708090    neutral    112    128    144

In [20]:
#writing a file
jsondata.to_csv(r"C:\Users\selvi\Downloads\colorsjson.csv")

In [38]:
#reading txt file with tab as seperator and including headers

head_col = ['id','name','dept','salary']
txtfile = pd.read_table(r"C:\Users\selvi\Downloads\employees.txt",header=None,names=head_col,index_col='id')
txtfile.loc[103,'dept']

'Sales'